### PR TITLE
SECURITY: Fixes race-conditions in login form, and makes failed login feedback equivalent.

### LINKED ISSUE #50: SECURITY: Race-conditions in login form, and login feedback tells user what accounts are/aren't registered.
Currently, the user can tell if a user is or is not registered based on failed login attempt. This is poor security, and allows brute force attempts to check for existing users before trying passwords.

The registration page will still block duplicate usernames, but it isn't as easily brute forced because a successful registration will make a valid user on the database (before feedback is given), which at least requires minimal effort to take account of when trying to brute force logins.

### PR DESCRIPTION
**Pull request by StudentKyle**
Closes #50 
Currently, the user can tell if a user is or is not registered based on failed login attempt. This is poor security, and allows brute force attempts to check for existing users before trying passwords.

The registration page will still block duplicate usernames, but it isn't as easily brute forced because a successful registration will make a valid user on the database (before feedback is given), which at least requires minimal effort to take account of when trying to brute force logins.

This PR simply makes the login failed feedback equivalent, and patches the race conditions present from handling the database queries synchronously (by restoring the asynchronous behavior, and adding awaits and returns.)

### CODE REVIEW

**Comment by StudentKyle** [comment]
Do not merge yet, I've found other security vulnerabilities introduced via PR https://github.com/owal7428/CSCI-3308-Group-5-Project/pull/45

**Comment by StudentKyle** [comment]
Okay, that should be it. @owal7428 @zane-perry if one of you could check that would be appreciated.

**Comment by StudentKyle** [comment]
I believe I've maintained the behavior zane added; just improving the security of it.

**Review by owal7428 — CHANGES_REQUESTED** [review]
I would recommend that you don't move the render functionality to an external handler and instead keep it inside the post method as it was previously.

**Comment by StudentKyle** [comment]
It is in the post request. I just added that function to reduce repeat code. The first way I implemented it is as you suggest, but I found much of the code redundant.

**Comment by StudentKyle** [comment]
See commit [50b66f4](https://github.com/owal7428/CSCI-3308-Group-5-Project/pull/51/commits/50b66f453febea29e18bd4923d5d15f78d2d1074) for where I made that change

**Comment by vincedbowen** [comment]
From my testing, the login fix works perfectly, but I am allowed to create unlimited duplicate usernames! Please look to fix that :)

**Comment by StudentKyle** [comment]
Did you make sure to re-make the database? When running docker compose down, add the -v flag to remove previously existing volumes.

**Pull request merged**
